name: Build Docker image
 
on:
  push: {}
 
jobs:
  build:
  runs-on: ubuntu-20.04
  permissions:
    contents: read
    id-token: write
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Depot CLI
      uses: depot/setup-action@v1
    - name: Build and push Docker images
      uses: depot/build-push-action@v1

      with:
        project: <your-depot-project-id>
        # Pass project token or user access token if you're not 
        # using OIDC + token authentication
        token: ${{ secrets.DEPOT_TOKEN }}

