 name: Build Docker image
     
    on:
      push: {}
     
    jobs:
      build:
        runs-on: ubuntu-20.04
        steps:
          - name: Checkout repo
            uses: actions/checkout@v3
        - name: Set up Docker CLI
            uses: docker/setup-buildx-action@v3
          - name: Build and push Docker images
            uses: docker/build-push-action@v5
            with:
              context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
